# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('role', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('software', models.CharField(default='', max_length=128)),
                ('tags', models.CharField(default='', max_length=64)),
                ('idle', models.BooleanField(default=True)),
                ('vginfo', models.TextField(null=True)),
                ('memory_total', models.IntegerField(default=0)),
                ('memory_used', models.IntegerField(default=0)),
                ('memory_free', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hd_mesos.HostInfo')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Hostgroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hd_mesos.HostGroup')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskid', models.CharField(default='', max_length=48)),
                ('taskname', models.CharField(default='', max_length=32)),
                ('acked', models.BooleanField(default=False)),
                ('star_time', models.DateTimeField()),
                ('hosts', models.TextField()),
                ('status', models.CharField(default='Running', max_length=50)),
                ('result', models.TextField(null=True)),
                ('date_done', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Shell_Task',
            fields=[
                ('user_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hd_mesos.User_Task')),
                ('shell_cmd', models.CharField(max_length=128)),
            ],
            bases=('hd_mesos.user_task',),
        ),
        migrations.CreateModel(
            name='User_Yum_Task',
            fields=[
                ('user_task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hd_mesos.User_Task')),
                ('soft_list', models.TextField(null=True)),
            ],
            bases=('hd_mesos.user_task',),
        ),
        migrations.AddField(
            model_name='user_task',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hd_mesos.HostGroup'),
        ),
        migrations.AddField(
            model_name='host_group',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hd_mesos.HostInfo'),
        ),
    ]
