# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host_group',
            unique_together=set([('ip', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='user_hostgroup',
            unique_together=set([('username', 'group')]),
        ),
    ]
