# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostip_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=16)),
                ('port', models.IntegerField(default=3306)),
            ],
        ),
        migrations.CreateModel(
            name='MysqlAduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('mysqluser', models.CharField(max_length=64)),
                ('mysqlhost', models.CharField(default='', max_length=16)),
                ('login_host', models.CharField(default='localhost', max_length=16)),
                ('pridate', models.DateTimeField(auto_now=True)),
                ('pri_database', models.CharField(default='', max_length=32)),
                ('pri_table', models.CharField(default='', max_length=32)),
                ('privilege', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('option', models.CharField(max_length=10)),
                ('mysqlhost', models.CharField(max_length=16)),
                ('mysqluser', models.CharField(max_length=64)),
                ('pridate', models.DateTimeField(auto_now_add=True)),
                ('pri_database', models.CharField(default='', max_length=32)),
                ('pri_table', models.CharField(default='', max_length=32)),
                ('privilege', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptInfo',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'shell'), (2, 'palybook')])),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SidInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=32)),
                ('sidname', models.CharField(max_length=32)),
                ('hostip', models.CharField(max_length=16)),
                ('socketpath', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('data_size', models.CharField(max_length=6)),
                ('buffer_pool', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('replpassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softname', models.CharField(max_length=16)),
                ('version', models.TextField(default='')),
            ],
        ),
    ]
